/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.bancodedados.view;

import fatec.bancodedados.dao.ClienteDAO;
import fatec.bancodedados.dao.NotaFiscalDAO;
import fatec.bancodedados.dao.ProdutoDAO;
import fatec.bancodedados.model.Cliente;
import fatec.bancodedados.model.NotaFiscal;
import fatec.bancodedados.model.Produto;
import fatec.bancodedados.model.ProdutoNota;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isaqu
 */
public class DetalhesNotaFiscal extends javax.swing.JFrame {

    private NotaFiscal nf;
    private LancamentoNotaFiscal telaPrincipal;
    private DefaultTableModel tblProdutosModel;

    /**
     * Creates new form DetalhesNotaFiscal
     *
     * @param nf
     */
    public DetalhesNotaFiscal(NotaFiscal nf, LancamentoNotaFiscal telaPrincipal) {
        initComponents();
        this.nf = nf;
        tblProdutosModel = (DefaultTableModel) TBL_Produtos.getModel();
        this.telaPrincipal = telaPrincipal;
        carregarDados();
    }

    public DetalhesNotaFiscal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NomeClineteInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DataVendaInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_Produtos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        SubTotalInput = new javax.swing.JTextField();
        CancelarNotaBotao = new javax.swing.JButton();
        StatusInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes Nota");

        jLabel1.setText("Nome do cliente:");

        NomeClineteInput.setEnabled(false);

        jLabel2.setText("Data da Venda:");

        DataVendaInput.setEnabled(false);

        TBL_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodProduto", "Nome", "Valor Unit.", "Quantidade", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBL_Produtos);
        if (TBL_Produtos.getColumnModel().getColumnCount() > 0) {
            TBL_Produtos.getColumnModel().getColumn(0).setResizable(false);
            TBL_Produtos.getColumnModel().getColumn(1).setResizable(false);
            TBL_Produtos.getColumnModel().getColumn(2).setResizable(false);
            TBL_Produtos.getColumnModel().getColumn(3).setResizable(false);
            TBL_Produtos.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel3.setText("Subtotal");

        SubTotalInput.setEnabled(false);

        CancelarNotaBotao.setText("Cancelar");
        CancelarNotaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarNotaBotaoActionPerformed(evt);
            }
        });

        StatusInput.setEnabled(false);

        jLabel4.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(NomeClineteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(DataVendaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelarNotaBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(SubTotalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StatusInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeClineteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataVendaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CancelarNotaBotao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubTotalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarNotaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarNotaBotaoActionPerformed

        if (!nf.isStatus()) {
            JOptionPane.showMessageDialog(this, "Essa nota fiscal já foi cancelada!");
            return;
        }

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja cancelar a Nota Fiscal Nº " + nf.getCodNota() + "?",
                "Confirmação de Cancelamento",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.NO_OPTION) {
            return;
        }

        NotaFiscalDAO nDAO = new NotaFiscalDAO();
        nDAO.cancelarNotaFiscal(nf.getCodNota());
        nf.setStatus(false);

        JOptionPane.showMessageDialog(this, "Nota Fiscal cancelada com sucesso!");
        
        telaPrincipal.carregarNotasFiscais();
        this.dispose();
    }//GEN-LAST:event_CancelarNotaBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesNotaFiscal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarNotaBotao;
    private javax.swing.JTextField DataVendaInput;
    private javax.swing.JTextField NomeClineteInput;
    private javax.swing.JTextField StatusInput;
    private javax.swing.JTextField SubTotalInput;
    private javax.swing.JTable TBL_Produtos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
   private void carregarDados() {
        DataVendaInput.setText(nf.getDataVenda().toString());

        Cliente nfCliente = new ClienteDAO().getCliente(nf.getCliente().getCpf());

        NomeClineteInput.setText(nfCliente.getNome());
        SubTotalInput.setText(Double.toString(nf.getSubTotal()));
        StatusInput.setText(nf.isStatus() ? "Autorizada" : "Cancelada");

        List<ProdutoNota> nfProdutos = nf.getItens();

        for (ProdutoNota pn : nfProdutos) {
            Produto p = pn.getProduto();
            tblProdutosModel.addRow(new Object[]{
                p.getCodProd(),
                p.getNome(),
                p.getPrecoVenda(),
                pn.getQtdVendida(),
                p.getPrecoVenda() * pn.getQtdVendida(),
            });
        }
    }
}
