/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Component;
import javax.swing.BoxLayout;

/**
 *
 * @author Beatriz Camargo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        modificarMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarradeOpcoes = new javax.swing.JMenuBar();
        OpcaoNovoCliente = new javax.swing.JMenu();
        CriarItem = new javax.swing.JMenuItem();
        EditarItem = new javax.swing.JMenuItem();
        ListarItem = new javax.swing.JMenuItem();
        ExcluirItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarradeOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        OpcaoNovoCliente.setText("Cliente");
        OpcaoNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoNovoClienteActionPerformed(evt);
            }
        });

        CriarItem.setText("Criar");
        CriarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarItemActionPerformed(evt);
            }
        });
        OpcaoNovoCliente.add(CriarItem);

        EditarItem.setText("Editar");
        EditarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarItemActionPerformed(evt);
            }
        });
        OpcaoNovoCliente.add(EditarItem);

        ListarItem.setText("Listar");
        ListarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarItemActionPerformed(evt);
            }
        });
        OpcaoNovoCliente.add(ListarItem);

        ExcluirItem.setText("Excluir");
        ExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirItemActionPerformed(evt);
            }
        });
        OpcaoNovoCliente.add(ExcluirItem);

        BarradeOpcoes.add(OpcaoNovoCliente);

        jMenu1.setText("jMenu1");
        BarradeOpcoes.add(jMenu1);

        setJMenuBar(BarradeOpcoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CriarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarItemActionPerformed

        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_CriarItemActionPerformed

    private void EditarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarItemActionPerformed
        new EditarCliente().setVisible(true);
    }//GEN-LAST:event_EditarItemActionPerformed

    private void ListarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarItemActionPerformed
        new ListarClientes().setVisible(true);
    }//GEN-LAST:event_ListarItemActionPerformed

    private void ExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirItemActionPerformed
        new ExcluirCliente().setVisible(true);
    }//GEN-LAST:event_ExcluirItemActionPerformed

    private void OpcaoNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoNovoClienteActionPerformed
        
    }//GEN-LAST:event_OpcaoNovoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarradeOpcoes;
    private javax.swing.JMenuItem CriarItem;
    private javax.swing.JMenuItem EditarItem;
    private javax.swing.JMenuItem ExcluirItem;
    private javax.swing.JMenuItem ListarItem;
    private javax.swing.JMenu OpcaoNovoCliente;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
    private void modificarMenu(){
        BarradeOpcoes.setLayout(new BoxLayout(BarradeOpcoes, BoxLayout.Y_AXIS));
        jMenu1.setAlignmentX(Component.LEFT_ALIGNMENT);
   }

}
