/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

//TODO: Aguardando a classe Endereco

import fatec.bancodedados.dao.ClienteDAO;
import fatec.bancodedados.dao.EnderecoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import fatec.bancodedados.model.Cliente;
import fatec.bancodedados.model.Endereco;
import static service.viaCEPService.buscarEnderecoPorCep;

/**
 *
 * @author Beatriz Camargo
 */
public class MenuClientes extends javax.swing.JFrame {
    private DefaultTableModel tblClienteModel;

    public MenuClientes() {
        initComponents();
        tblClienteModel = (DefaultTableModel) ClienteTable.getModel();
        carregarClientes();
        CodigoGroupInput.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarBotao = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        FormulárioCliente = new javax.swing.JPanel();
        TelefoneInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NomeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CEPLabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CodigoGroupInput = new javax.swing.JPanel();
        CodInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BotaoBuscarCEP = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LogradouroInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BairroInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        UfInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CidadeInput = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ComplementoInput = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        NumeroInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClienteTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        criarBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/add.png"))); // NOI18N
        criarBotao.setText("Salvar");
        criarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarBotaoActionPerformed(evt);
            }
        });

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });

        ExcluirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/delete.png"))); // NOI18N
        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/pencil.png"))); // NOI18N
        BotaoEditar.setText("Editar");
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome ");

        jLabel3.setText("Cep");

        jLabel4.setText("Email");

        jLabel5.setText("Telefone");

        CodInput.setEnabled(false);

        jLabel6.setText("Código ");

        javax.swing.GroupLayout CodigoGroupInputLayout = new javax.swing.GroupLayout(CodigoGroupInput);
        CodigoGroupInput.setLayout(CodigoGroupInputLayout);
        CodigoGroupInputLayout.setHorizontalGroup(
            CodigoGroupInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CodigoGroupInputLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CodigoGroupInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CodigoGroupInputLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addComponent(CodInput, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        CodigoGroupInputLayout.setVerticalGroup(
            CodigoGroupInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CodigoGroupInputLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CodInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BotaoBuscarCEP.setText("Buscar");
        BotaoBuscarCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarCEPActionPerformed(evt);
            }
        });

        jLabel7.setText("Logradouro: ");

        LogradouroInput.setEnabled(false);

        jLabel8.setText("Bairro:");

        BairroInput.setEnabled(false);

        jLabel9.setText("UF");

        UfInput.setEnabled(false);

        jLabel10.setText("Cidade");

        CidadeInput.setEnabled(false);

        jLabel11.setText("Complemento");

        ComplementoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplementoInputActionPerformed(evt);
            }
        });

        jLabel12.setText("Número");

        javax.swing.GroupLayout FormulárioClienteLayout = new javax.swing.GroupLayout(FormulárioCliente);
        FormulárioCliente.setLayout(FormulárioClienteLayout);
        FormulárioClienteLayout.setHorizontalGroup(
            FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormulárioClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormulárioClienteLayout.createSequentialGroup()
                        .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(TelefoneInput, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                    .addGroup(FormulárioClienteLayout.createSequentialGroup()
                        .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BairroInput, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormulárioClienteLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel10))
                            .addGroup(FormulárioClienteLayout.createSequentialGroup()
                                .addComponent(UfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CidadeInput))))
                    .addGroup(FormulárioClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addContainerGap())
                    .addGroup(FormulárioClienteLayout.createSequentialGroup()
                        .addComponent(LogradouroInput, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NumeroInput))
                    .addGroup(FormulárioClienteLayout.createSequentialGroup()
                        .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(FormulárioClienteLayout.createSequentialGroup()
                                .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(CEPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoBuscarCEP))
                            .addComponent(jLabel11)
                            .addComponent(ComplementoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CodigoGroupInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        FormulárioClienteLayout.setVerticalGroup(
            FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormulárioClienteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(CodigoGroupInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormulárioClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormulárioClienteLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBuscarCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogradouroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormulárioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BairroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CidadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComplementoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/userIcon.png"))); // NOI18N
        jLabel2.setText("Gerenciamento de Clientes");

        ClienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "CEP", "Email", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClienteTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(ClienteTable);
        if (ClienteTable.getColumnModel().getColumnCount() > 0) {
            ClienteTable.getColumnModel().getColumn(0).setResizable(false);
            ClienteTable.getColumnModel().getColumn(1).setResizable(false);
            ClienteTable.getColumnModel().getColumn(2).setResizable(false);
            ClienteTable.getColumnModel().getColumn(3).setResizable(false);
            ClienteTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormulárioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(criarBotao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotaoLimpar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FormulárioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(criarBotao)
                            .addComponent(ExcluirButton)
                            .addComponent(BotaoEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoLimpar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarBotaoActionPerformed
        String nome = NomeField.getText().trim();
        String email = EmailLabel.getText().trim();
        String telefone = TelefoneInput.getText().trim();
        String cep = CEPLabel.getText().trim();

        if (nome.isEmpty() || email.isEmpty() || telefone.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Os campos Nome, Email e Telefone são obrigatórios.",
                "Erro de Validação",
                JOptionPane.ERROR_MESSAGE 
            );
            return;
        }
        if(CodigoGroupInput.isVisible()){
            //Editar
            Cliente cl = new Cliente();
            cl.setCod(Integer.parseInt(CodInput.getText()));
            cl.setEmail(email);
            cl.setNome(nome);
            cl.setTelefone(telefone);
            
            
            EnderecoDAO endDAO = new EnderecoDAO();
            
            Endereco end = endDAO.buscarEnderecoPorCodCliente(cl.getCod());
            
            end.setLogradouro(LogradouroInput.getText());
            end.setNumCasa(NumeroInput.getText());
            end.setBairro(BairroInput.getText());
            end.setUf(UfInput.getText());
            end.setCidade(CidadeInput.getText());
            end.setCep(CEPLabel.getText());
            end.setComplemento(ComplementoInput.getText());

            System.out.println("Código: " + end.getCodEndereco());
            endDAO.editar(end);
            
            cl.setCodEndereco(end.getCodEndereco());
            
            ClienteDAO clDAO = new ClienteDAO();
            clDAO.editar(cl);
            carregarClientes();
        }else{
            //Criar
            Endereco clEnd = new Endereco(
                    LogradouroInput.getText(),
                    ComplementoInput.getText(),
                    NumeroInput.getText(),
                    BairroInput.getText(),
                    UfInput.getText(),
                    CidadeInput.getText(),
                    cep
            );
            EnderecoDAO clEndDAO = new EnderecoDAO();
            //Inserir endereco deve retronar o ID;
            int codEndereco = clEndDAO.inserir(clEnd);
            Cliente cl = new Cliente(nome,codEndereco,email,telefone);
            ClienteDAO clDAO = new ClienteDAO();
            clDAO.inserir(cl);
            carregarClientes();        
        }
        limparFormulario();
    }//GEN-LAST:event_criarBotaoActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        if(ClienteTable.getSelectedRowCount() == 1){
            int reposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Exclusão", JOptionPane.YES_NO_OPTION);
            if(reposta == JOptionPane.YES_OPTION){
                ClienteDAO clDAO = new ClienteDAO();
                EnderecoDAO endDAO = new EnderecoDAO();
                int linha = ClienteTable.getSelectedRow();
                int cod = Integer.parseInt(ClienteTable.getValueAt(linha, 0).toString());
                Endereco clEndereco = endDAO.buscarEnderecoPorCodCliente(cod);
                if(clEndereco == null){
                    JOptionPane.showMessageDialog(this, "Endereço do cliente não encontrado.");
                } else {
                    clDAO.excluir(cod);
                    endDAO.excluir(clEndereco.getCodEndereco());
                    tblClienteModel.removeRow(ClienteTable.getSelectedRow());
                }
            }
        }else if(ClienteTable.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Tabela vazia.");
        }else{
            JOptionPane.showMessageDialog(this, "Por favor, seleciona apenas uma linha para a operação.");
        }
        limparFormulario();
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        limparFormulario();
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarActionPerformed
        if (ClienteTable.getSelectedRowCount() == 1) {
            int linha = ClienteTable.getSelectedRow();
            int cod = Integer.parseInt(ClienteTable.getValueAt(linha, 0).toString());
            CodigoGroupInput.setVisible(true);
            CodInput.setText(String.valueOf(cod));
            
            //Pegar Endereco por cod cliente
            EnderecoDAO endDAO = new EnderecoDAO();
            Endereco endCl = endDAO.buscarEnderecoPorCodCliente(cod);

            NomeField.setText(ClienteTable.getValueAt(linha, 1).toString());
            EmailLabel.setText(ClienteTable.getValueAt(linha, 3).toString());
            TelefoneInput.setText(ClienteTable.getValueAt(linha, 4).toString());
            CEPLabel.setText(ClienteTable.getValueAt(linha, 2).toString());
            preencherEndereco(endCl);
            
        } else if (ClienteTable.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tabela vazia.");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione apenas uma linha para a operação.");
        }
    }//GEN-LAST:event_BotaoEditarActionPerformed

    private void BotaoBuscarCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarCEPActionPerformed
        String cep = CEPLabel.getText().trim();

        Endereco cepBuscado;
        try {
            cepBuscado = buscarEnderecoPorCep(cep);
            if(cepBuscado == null){
                JOptionPane.showMessageDialog(this, "CEP inválido", "Erro ao buscar CEP", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            preencherEndereco(cepBuscado);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar CEP", "Erro Interno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoBuscarCEPActionPerformed

    private void ComplementoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplementoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComplementoInputActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClientes().setVisible(true);
            }
        });
    }
    private void carregarClientes() {
        List<Cliente> clientes = new ClienteDAO().getClientes();
        tblClienteModel.setRowCount(0);
        for (Cliente c : clientes) {
            EnderecoDAO endDAO = new EnderecoDAO();
            Endereco clEnd = endDAO.buscarEnderecoPorCodCliente(c.getCod());
            tblClienteModel.addRow(new Object[]{
                c.getCod(),
                c.getNome(),
                clEnd.getCep(),
                c.getEmail(),
                c.getTelefone()
            });
        }
    }
    
    private void selecionarCliente() {
        if (ClienteTable.getSelectedRowCount() == 1) {
           int linha = ClienteTable.getSelectedRow();
           int cod = Integer.parseInt(ClienteTable.getValueAt(linha, 0).toString());
           CodigoGroupInput.setVisible(true);
           CodInput.setText(String.valueOf(cod));

           NomeField.setText(ClienteTable.getValueAt(linha, 1).toString());
           CEPLabel.setText(ClienteTable.getValueAt(linha, 2).toString());
           EmailLabel.setText(ClienteTable.getValueAt(linha, 3).toString());
           TelefoneInput.setText(ClienteTable.getValueAt(linha, 4).toString());

       } else if (ClienteTable.getRowCount() == 0) {
           JOptionPane.showMessageDialog(this, "Tabela vazia.");
       } else {
           JOptionPane.showMessageDialog(this, "Por favor, selecione apenas uma linha para a operação.");
       }
    }
    
    private void limparFormulario(){
        CodigoGroupInput.setVisible(false);
        EmailLabel.setText("");
        NomeField.setText("");
        TelefoneInput.setText("");
        CEPLabel.setText("");
        NumeroInput.setText("");
        LogradouroInput.setText("");
        BairroInput.setText("");
        UfInput.setText("");
        CidadeInput.setText("");
        ComplementoInput.setText("");
    }
    
    private void preencherEndereco(Endereco end){
        LogradouroInput.setText(end.getLogradouro());
        BairroInput.setText(end.getBairro());
        UfInput.setText(end.getUf());
        CidadeInput.setText(end.getCidade());
        ComplementoInput.setText(end.getComplemento());
        NumeroInput.setText(end.getNumCasa());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroInput;
    private javax.swing.JButton BotaoBuscarCEP;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JTextField CEPLabel;
    private javax.swing.JTextField CidadeInput;
    private javax.swing.JTable ClienteTable;
    private javax.swing.JTextField CodInput;
    private javax.swing.JPanel CodigoGroupInput;
    private javax.swing.JTextField ComplementoInput;
    private javax.swing.JTextField EmailLabel;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JPanel FormulárioCliente;
    private javax.swing.JTextField LogradouroInput;
    private javax.swing.JTextField NomeField;
    private javax.swing.JTextField NumeroInput;
    private javax.swing.JTextField TelefoneInput;
    private javax.swing.JTextField UfInput;
    private javax.swing.JButton criarBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
