/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

<<<<<<< Updated upstream
import java.awt.Component;
import javax.swing.BoxLayout;
=======
import dao.ClienteDAO;
import java.awt.Component;
import java.util.List;
import javax.swing.BoxLayout;
import model.Cliente;
>>>>>>> Stashed changes

/**
 *
 * @author Beatriz Camargo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        modificarMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BarradeOpcoes = new javax.swing.JMenuBar();
<<<<<<< Updated upstream
        OpcaoNovoCliente = new javax.swing.JMenu();
        CriarItem = new javax.swing.JMenuItem();
        EditarItem = new javax.swing.JMenuItem();
        ListarItem = new javax.swing.JMenuItem();
        ExcluirItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarradeOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        OpcaoNovoCliente.setText("Cliente");
        OpcaoNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoNovoClienteActionPerformed(evt);
            }
        });
=======
        ProdutoMenu = new javax.swing.JMenu();
        CienteMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProdutoMenu.setText("Produto");
        BarradeOpcoes.add(ProdutoMenu);
>>>>>>> Stashed changes

        CienteMenu.setText("Cliente");
        BarradeOpcoes.add(CienteMenu);

        jMenu1.setText("jMenu1");
        BarradeOpcoes.add(jMenu1);

        setJMenuBar(BarradeOpcoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarradeOpcoes;
<<<<<<< Updated upstream
    private javax.swing.JMenuItem CriarItem;
    private javax.swing.JMenuItem EditarItem;
    private javax.swing.JMenuItem ExcluirItem;
    private javax.swing.JMenuItem ListarItem;
    private javax.swing.JMenu OpcaoNovoCliente;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
    private void modificarMenu(){
        BarradeOpcoes.setLayout(new BoxLayout(BarradeOpcoes, BoxLayout.Y_AXIS));
        jMenu1.setAlignmentX(Component.LEFT_ALIGNMENT);
   }

=======
    private javax.swing.JMenu CienteMenu;
    private javax.swing.JMenu ProdutoMenu;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
    private void modificarMenu(){
        BarradeOpcoes.setLayout(new BoxLayout(BarradeOpcoes, BoxLayout.Y_AXIS));
        CienteMenu.setAlignmentX(Component.LEFT_ALIGNMENT);
        ProdutoMenu.setAlignmentX(Component.LEFT_ALIGNMENT);
   }
>>>>>>> Stashed changes
}

